import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (path: string) => readFileSync(join(root, path), 'utf8');
const shared = read('AGENTS.shared.md'), next = read('skills/next/SKILL.md'), slices = read('design/30-slices.md');
const skills = readdirSync(join(root, 'skills')).map(name => ({ name, text: read(`skills/${name}/SKILL.md`) }));
const docs = ['00-brief', '10-design', '20-contract', '30-slices'].map(name => read(`design/${name}.md`).split(/^## Landed\s*$/m)[0]);
const removed = ['Test-DesignState', 'Test-DesignDrift', 'Test-Companion', 'Test-WriteSurface', 'Test-CIWorkflow', 'Update-WorkMirror', 'Update-DesignProjection', 'Update-SlicesDocument', 'Read-DesignState', 'Get-NextOrientation', 'Get-AgentKitNext'];
const commands = ['track', 'clean', 'hold', 'resume', 'tune', 'handoff', 'spec', 'docs', 'slice', 'check', 'resolve', 'pr', 'help', 'autoupdate'];
test('shared lets a build continue in the same session', () => assert.match(shared, /continues in the same session/));
test('shared has no session-boundary rule', () => assert.doesNotMatch(shared, /session boundar|fresh session/i));
test('shared keeps the no-attribution rule', () => assert.match(shared, /No AI attribution, anywhere/));
test('shared keeps merging delegated to merge-pull-request.ts alone', () => assert.match(shared, /Merging is delegated to `tools\/merge-pull-request\.ts` and nothing else/));
test('shared has no design freeze', () => assert.doesNotMatch(shared, /FROZEN\.md/));
test('next builds slice after slice in this same session', () => assert.match(next, /in this same session/));
test('next merges only through merge-pull-request.ts', () => assert.match(next, /tools\/merge-pull-request\.ts/));
test('next never stashes a dirty tree', () => { assert.match(next, /never stash/i); assert.doesNotMatch(next, /git stash/); });
test('next treats the Landed index as done and never rebuilds it', () => { assert.match(next, /## Landed/); assert.match(next, /none is ever rebuilt/); });
test('live design cites no removed tool or command', () => { for (const doc of docs) { for (const name of removed) assert.ok(!doc.includes(name)); for (const name of commands) assert.doesNotMatch(doc, new RegExp('`/' + name + '[` ]')); } });
test('live design has no session boundary or design freeze', () => { for (const doc of docs) assert.doesNotMatch(doc, /session boundar|FROZEN\.md/i); });
test('every slice heading has a Status line', () => { for (const m of slices.matchAll(/^#{2,3} S(\d+)\b[^\n]*\n((?:(?!^#{1,3} ).*\n?)*)/gm)) assert.match(m[2], /^Status: (todo|done)\s*$/m, m[1]); });
test('migrated S1-S32 remain a Landed index rather than buildable headings', () => { assert.match(slices, /^## Landed\s*$/m); for (let n = 1; n <= 32; n++) { assert.match(slices, new RegExp('\\|\\s*\\*\\*S' + n + '\\*\\*\\s*\\|')); assert.doesNotMatch(slices, new RegExp('^#{2,3} S' + n + '\\b', 'm')); } });
test('skills never end a run with a session-boundary banner', () => { for (const s of skills) assert.doesNotMatch(s.text, /session boundary/i, s.name); });
test('skills reference no removed tool', () => { for (const s of skills) for (const name of removed) assert.ok(!s.text.includes(name), s.name); });
test('skills invoke no removed command', () => { for (const s of skills) for (const name of commands) assert.doesNotMatch(s.text, new RegExp('`/' + name + '[` ]'), s.name); });
test('skills cite COMPANIONS.md only to migrate it away', () => { for (const s of skills.filter(s => s.name !== 'install-all')) assert.doesNotMatch(s.text, /COMPANIONS\.md/, s.name); });
test('guard detects a removed tool and command when cited', () => { assert.match('run tools/Test-DesignState.ps1', /Test-DesignState/); assert.match('then run `/track` to sync', /`\/track[` ]/); });
test('next appends its decisions to 90-decisions.md in the slice pull request', () => { assert.match(next, /Record the slice's decisions in `design\/90-decisions\.md` in this same branch/); assert.match(next, /Never edit or remove an existing entry/); });
test('shared keeps the decision log current and append-only', () => assert.match(shared, /The one part kept current is `90-decisions\.md`\.[^\n]*only appends/));
